
-- Insert all admin permissions for all modules and actions
-- First delete existing admin permissions to avoid conflicts
DELETE FROM public.role_permissions WHERE role = 'admin';

-- Insert all permissions for admin with allowed = true
INSERT INTO public.role_permissions (role, module, action, allowed) VALUES
  ('admin', 'dashboard', 'view', true),
  ('admin', 'suppliers', 'view', true),
  ('admin', 'suppliers', 'create', true),
  ('admin', 'suppliers', 'edit', true),
  ('admin', 'suppliers', 'delete', true),
  ('admin', 'suppliers', 'export', true),
  ('admin', 'products', 'view', true),
  ('admin', 'products', 'create', true),
  ('admin', 'products', 'edit', true),
  ('admin', 'products', 'delete', true),
  ('admin', 'products', 'edit_prices', true),
  ('admin', 'products', 'export', true),
  ('admin', 'orders', 'view', true),
  ('admin', 'orders', 'create', true),
  ('admin', 'orders', 'edit', true),
  ('admin', 'orders', 'delete', true),
  ('admin', 'orders', 'export', true),
  ('admin', 'inventory', 'view', true),
  ('admin', 'inventory', 'create', true),
  ('admin', 'inventory', 'edit', true),
  ('admin', 'inventory', 'delete', true),
  ('admin', 'inventory', 'export', true),
  ('admin', 'sales', 'view', true),
  ('admin', 'sales', 'create', true),
  ('admin', 'sales', 'edit', true),
  ('admin', 'sales', 'cancel', true),
  ('admin', 'sales', 'export', true),
  ('admin', 'pos', 'view', true),
  ('admin', 'pos', 'use', true),
  ('admin', 'invoices', 'view', true),
  ('admin', 'invoices', 'create', true),
  ('admin', 'invoices', 'edit', true),
  ('admin', 'invoices', 'delete', true),
  ('admin', 'invoices', 'export', true),
  ('admin', 'expenses', 'view', true),
  ('admin', 'expenses', 'create', true),
  ('admin', 'expenses', 'edit', true),
  ('admin', 'expenses', 'delete', true),
  ('admin', 'expenses', 'export', true),
  ('admin', 'reports', 'view', true),
  ('admin', 'reports', 'export', true),
  ('admin', 'users', 'view', true),
  ('admin', 'users', 'create', true),
  ('admin', 'users', 'edit', true),
  ('admin', 'users', 'delete', true),
  ('admin', 'import', 'view', true),
  ('admin', 'import', 'use', true),
  ('admin', 'settings', 'view', true),
  ('admin', 'settings', 'edit', true),
  ('admin', 'permissions', 'view', true),
  ('admin', 'permissions', 'edit', true);
